env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  {
    '@typescript-eslint/no-inferrable-types': 'off',
    '@typescript-eslint/no-unused-vars': 'warn',
    '@typescript-eslint/no-redeclare': 'warn',
    '@typescript-eslint/naming-convention':
      [
        'warn',
        { selector: 'default', format: ['camelCase'] },
        {
          selector: 'variableLike',
          format: ['camelCase', 'UPPER_CASE', 'PascalCase'],
        },
        { selector: 'typeLike', format: ['PascalCase'] },
      ],
    '@typescript-eslint/prefer-optional-chain': 'warn',

    'import/no-default-export': 'off',
    'import/prefer-default-export': 'off',
    'import/extensions':
      [
        'error',
        'ignorePackages',
        { 'js': 'never', 'jsx': 'never', 'ts': 'never', 'tsx': 'never' },
      ],

    'react/react-in-jsx-scope': 'off',
    'react/jsx-filename-extension':
      [2, { 'extensions': ['.js', '.jsx', '.ts', '.tsx'] }],
    'react/no-unescaped-entities': 0,
    'react/jsx-props-no-spreading': 'warn',

    'no-unused-vars': 'off',
    'no-undef': 'off',
    'no-shadow': 'off',
    'jsx-quotes': [2, 'prefer-single'],
  }
settings:
  {
    'import/resolver':
      {
        node: { extensions: ['.js', '.jsx', '.json', '.ts', '.tsx', '.d.ts'] },
      },
  }
